<Project>
  <PropertyGroup>
    <Version>0.0.0</Version>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Platforms>x64</Platforms>
    <PlatformTarget>$(Platform)</PlatformTarget>
    <TargetFramework>net9.0</TargetFramework>

    <Copyright>Copyright (C) 2025 Creatorly.company</Copyright>
    <Company>Creatorly.company</Company>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>

    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- general packages -->
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.7.0.110445">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Test projects -->
  <ItemGroup Condition="$(MSBuildProjectName.Contains('Tests'))">
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Bogus" Version="35.6.4" />
    <PackageReference Include="AwesomeAssertions" Version="9.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="xunit.v3" Version="3.1.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>
</Project>
