name: "CI - {{ creatorly.project_name }}"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6

      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Install dependencies
        run: |
          make install

      - name: Lint code
        run: |
          make lint

      - name: Format code
        run: |
          make format

      - name: Run tests
        run: |
          pmake test

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
