name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run dotnet format
        run: just check-format

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: just build Release

      - name: Test
        run: just test Release
