CMD := if path_exists('/.dockerenv') == "false" { 'docker run --rm -u $(id -u):$(id -g) -v $(pwd):/workspaces/creatorly_project_name -v conan2-data:/home/dev/.conan2 -w /workspaces/creatorly_project_name creatorly_project_name-toolchain' } else { '' }

# build the docker image for ci
build-ci-docker:
    echo "Building Docker image..."
    docker volume create conan2-data
    docker build -t creatorly_project_name-toolchain --target ci --build-arg UID=$(id -u) .

setup:
    {{CMD}} rm -rf .venv
    {{CMD}} python3 -m venv .venv
    {{CMD}} .venv/bin/pip3 install -r requirements.txt

build profile build_type="Debug":
    {{CMD}} .venv/bin/conan install . --profile:host={{profile}} --profile:build={{profile}} --settings build_type={{build_type}} --build=missing
    {{CMD}} cmake --preset conan-{{lowercase(build_type)}}
    {{CMD}} cmake --build --preset conan-{{lowercase(build_type)}}

format:
    {{CMD}} clang-format -i $(find src -name '*.cpp' -o -name '*.h')

lint build_type="Debug":
    {{CMD}} clang-tidy -p build/{{build_type}} $(find src -name '*.cpp')

test build_type="Debug" output_dir="./tmp/test_results":
    {{CMD}} mkdir -p {{output_dir}}
    {{CMD}} cmake --build --preset conan-{{lowercase(build_type)}}
    {{CMD}} env GTEST_OUTPUT="xml:{{output_dir}}/" ctest --test-dir build/{{build_type}} --output-on-failure
    {{CMD}} gcovr -r . --object-directory=build/{{build_type}} --exclude '.*(tests).*' --xml -o {{output_dir}}/coverage.xml

